services:
  # PostgreSQL Database
  postgres:
    image: pgvector/pgvector:pg15
    container_name: smart-edu-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: smart-edu-db
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - smart-edu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smart-edu-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and sessions (optional but recommended)
  redis:
    image: redis:7-alpine
    container_name: smart-edu-dev-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - smart-edu-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Smart Edu Backend Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: smart-edu-dev-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      # Override specific variables for Docker environment
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:123@postgres:5432/smart-edu-db
      REDIS_URL: redis://redis:6379
      
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
    networks:
      - smart-edu-network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Prisma Studio (Database GUI)
  prisma-studio:
    image: node:20-alpine
    container_name: smart-edu-dev-prisma-studio
    restart: unless-stopped
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:123@postgres:5432/smart-edu-db
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npx prisma studio --hostname 0.0.0.0 --port 5555"
    networks:
      - smart-edu-network
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  smart-edu-network:
    driver: bridge
